version: "3.3"
services:
  api:
    image: todo.api
    container_name: todo_api
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: |
      sh -c "python manage.py migrate && gunicorn config.asgi:application -b 0.0.0.0:8000 -w 4 -k uvicorn.workers.UvicornWorker"

    depends_on:
      - 'postgres'

  postgres:
    image: postgres:10-alpine
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  todo-api:
    driver: local
