name: Testing and Deploy

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST_DO}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_PRIVATE_KEY_DO}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME_DO }} # User of the server you want to ssh into
          port: ${{ secrets.SSH_PORT_DO }}

          script: |
            cd todo-api 
            git pull origin master
            docker compose -f docker-compose.yml up -di --build
            echo 'Deployment successful to digital ocean'
